image:
  file: .gitpod.Dockerfile
tasks:
  - init: gradle compileKotlin
vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==
    - fwcd.kotlin@0.2.11:moh8IDanzsIlhtK2IeiLmQ==
